# Generated by Django 2.1.5 on 2020-07-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200707_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('Finance_Manager', 'approve payments'), ('Analyst', 'process vendor payment'))},
        ),
    ]
