# Generated by Django 2.1.5 on 2020-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20200707_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_report',
            name='payment',
            field=models.BooleanField(default=True, verbose_name='process vendor payment'),
        ),
    ]
